baseurl = "https://www.jkawamoto.info/"
languageCode = "ja"
title = "Junpei Kawamoto"
copyright = "&copy; 2016 Junpei Kawamoto"
theme = "hugo-strata-theme"

[params]
	# To provide some metadata for search engines feel free to add a few
  # information about you and your website.
	name = "Junpei Kawamoto"
	description = "Homepage of Junpei Kawamoto."

	# Enable Google Analytics by inserting your tracking code
	googleAnalytics = "UA-19410992-1"


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "avatar.jpg"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "**Junpei Kawamoto**, Ph.D. in Informatics.<br>Research scientist working with data mining, security, and privacy."
		# The icons will be shown if you enter your username
		twitter = "junkawamoto"
		github = "jkawamoto"
		dribbble = ""
		facebook = "junpei.kawamoto"
		googleplus = ""
		flickr = "junkawamoto"
		linkedin = "jkawamoto"
		youtube = "UCAImvZQSpr4dw6USxHNqDXg"
		btc = "1625kBbXoGRWRh92XcgLFik5E6PgV482sm"

		copyright = [
			"&copy; Junpei Kawamoto",
			"Design: [HTML5 UP](//html5up.net)",
			"[Little Kitune studio](https://www.littlekitune.org/)"
		]

		[[params.sidebar.nav]]
			title = "Blog"
			url = "/blogs/"

		[[params.sidebar.nav]]
			title = "Publications"
			url = "/publications/"

		[[params.sidebar.nav]]
			title = "Research"
			url = "/research/"

		[[params.sidebar.nav]]
			title = "Lectures"
			url = "/lectures/"

		[[params.sidebar.navja]]
			title = "日本語"
			url = "/japanese/"

		[[params.sidebar.navja]]
			title = "論文リスト"
			url = "/publications-ja/"

		[[params.sidebar.navja]]
			title = "メモ"
			url = "/blog-ja/"

		[[params.sidebar.navja]]
			title = "その他の活動"
			url = "/activity-ja/"

	[params.about]
		title = "Profile"
		content = '''
## Experience
- 2013.9 - 2016.6: Assist. Prof. at
	[Faculty of Information Science and Electrical Engineering](http://portal.isee.kyushu-u.ac.jp/e/),
	[Kyushu University](http://www.kyushu-u.ac.jp/en/)
- 2013.12 - 2016.6: Assist. Prof. at Faculty of
	[Science](http://www.sci.kyushu-u.ac.jp/e/) and [Engineering](http://www.eng.kyushu-u.ac.jp/e/index.html),
	[Kyushu University](http://www.kyushu-u.ac.jp/en/)
- 2013.9 - 2016.3: Research Fellow at
	[Institute of Systems, Information Technologies and Nanotechnologies](http://www.isit.or.jp/english/)
-	2012.4 - 2013.9: Research Fellow at
	[Grad. School of Systems and Info. Engineering](http://www.sie.tsukuba.ac.jp/english/),
	[University of Tsukuba](http://www.tsukuba.ac.jp/english/)
- 2012.1 - 2012.3: Expert Researcher at
	[National Institute of Information and Communications Technology](http://www.nict.go.jp/en/index.html)
- 2009.4 – 2011.12: Research Fellow  at
	[Japan Society for the Promotion of Science](http://www.jsps.go.jp/english/index.html)
- 2007.10 - 2008.3: Software Developer at
 	[Information-technology Promotion Agency, Japan](https://www.ipa.go.jp/index-e.html)

## Education
- 2008.10 - 2012.3: PhD. Informatics,
	[Graduate School of Informatics](http://www.i.kyoto-u.ac.jp/en/),
	[Kyoto University](http://www.kyoto-u.ac.jp/en)
- 2007.4 - 2008.9: M. Informatics,
	[Graduate School of Informatics](http://www.i.kyoto-u.ac.jp/en/),
	[Kyoto University](http://www.kyoto-u.ac.jp/en).
- 2003.4 – 2007.3: B. Eng.,
	[School of Informatics and Mathematical Science](http://www.s-im.t.kyoto-u.ac.jp/en?set_language=en),
	[Faculty of Eng.](http://www.t.kyoto-u.ac.jp/en),
	[Kyoto University](http://www.kyoto-u.ac.jp/en).

## Software
### Cloud Computing
- [roadie](https://jkawamoto.github.io/roadie/):
	A easy way to run your programs on Google Cloud Platform
- [roadie-gcp](https://jkawamoto.github.io/roadie-gcp/):
	A helper container to execute a program on Google Cloud Platform
- [ambassadors](https://jkawamoto.github.io/ambassadors/):
	Yet another Ambassador pattern over SSH

### Data mining
- [Review Graph Mining](https://rgmining.github.io): Finding fraud reviewers from review data in online shops.

### Open Data & Linked Data
- [fukuoka-city-community-space-finder](https://jkawamoto.github.io/fukuoka-city-community-space-finder/):
	Find Community Spaces in Fukuoka City and check reservation status of them.

### IoT
- [fplug-logger](https://jkawamoto.github.io/fplug-logger/):
	Continuously reporting data from Fujitsu's F-Plug

### Utilities
- [dsargparse](https://jkawamoto.github.io/dsargparse/):
	docstring based argparse
- [fgo](https://jkawamoto.github.io/fgo/):
	Build, upload, and create brew formula for golang application.
- [loci](https://jkawamoto.github.io/loci/):
	Testing remote CI scripts locally
- [gii](https://jkawamoto.github.io/gii/):
	Set repositories which doesn't belong golang project to .goimportsignore.
'''

	[params.portfolio]
		title = "Recent Work"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery]]
			image = "fulls/01.jpg"
			thumb = "thumbs/01.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/02.jpg"
			thumb = "thumbs/02.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/03.jpg"
			thumb = "thumbs/03.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/04.jpg"
			thumb = "thumbs/04.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/05.jpg"
			thumb = "thumbs/05.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/06.jpg"
			thumb = "thumbs/06.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."


	[params.contact]
		email = "junpei.kawamoto@acm.org"
